//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soapClientAlumno.servicios_Alumno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:class_api", ConfigurationName="servicios_Alumno.ClassroomWSPortType")]
    public interface ClassroomWSPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#BuscarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientAlumno.servicios_Alumno.RespuestaBuscarAlumno BuscarAlumno(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#BuscarAlumno", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<soapClientAlumno.servicios_Alumno.RespuestaBuscarAlumno> BuscarAlumnoAsync(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#Bienvenida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientAlumno.servicios_Alumno.RespuestaBienvenida Bienvenida(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#Bienvenida", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<soapClientAlumno.servicios_Alumno.RespuestaBienvenida> BienvenidaAsync(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#EvaluarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientAlumno.servicios_Alumno.RespuestaEvaluarAlumno EvaluarAlumno(string user, string pass, string matricula, int semestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#EvaluarAlumno", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<soapClientAlumno.servicios_Alumno.RespuestaEvaluarAlumno> EvaluarAlumnoAsync(string user, string pass, string matricula, int semestre);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaBuscarAlumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaEvaluarAlumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private float promedioField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        public float promedio {
            get {
                return this.promedioField;
            }
            set {
                this.promedioField = value;
                this.RaisePropertyChanged("promedio");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaBienvenida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClassroomWSPortTypeChannel : soapClientAlumno.servicios_Alumno.ClassroomWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassroomWSPortTypeClient : System.ServiceModel.ClientBase<soapClientAlumno.servicios_Alumno.ClassroomWSPortType>, soapClientAlumno.servicios_Alumno.ClassroomWSPortType {
        
        public ClassroomWSPortTypeClient() {
        }
        
        public ClassroomWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassroomWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassroomWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassroomWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public soapClientAlumno.servicios_Alumno.RespuestaBuscarAlumno BuscarAlumno(string user, string pass, string matricula) {
            return base.Channel.BuscarAlumno(user, pass, matricula);
        }
        
        public System.Threading.Tasks.Task<soapClientAlumno.servicios_Alumno.RespuestaBuscarAlumno> BuscarAlumnoAsync(string user, string pass, string matricula) {
            return base.Channel.BuscarAlumnoAsync(user, pass, matricula);
        }
        
        public soapClientAlumno.servicios_Alumno.RespuestaBienvenida Bienvenida(string user, string pass, string matricula) {
            return base.Channel.Bienvenida(user, pass, matricula);
        }
        
        public System.Threading.Tasks.Task<soapClientAlumno.servicios_Alumno.RespuestaBienvenida> BienvenidaAsync(string user, string pass, string matricula) {
            return base.Channel.BienvenidaAsync(user, pass, matricula);
        }
        
        public soapClientAlumno.servicios_Alumno.RespuestaEvaluarAlumno EvaluarAlumno(string user, string pass, string matricula, int semestre) {
            return base.Channel.EvaluarAlumno(user, pass, matricula, semestre);
        }
        
        public System.Threading.Tasks.Task<soapClientAlumno.servicios_Alumno.RespuestaEvaluarAlumno> EvaluarAlumnoAsync(string user, string pass, string matricula, int semestre) {
            return base.Channel.EvaluarAlumnoAsync(user, pass, matricula, semestre);
        }
    }
}
